### ISSUE TITLE
连续点击会动画会抖动

### ISSUE THREAD

**Issue by CatchaOG** [zhouatie/plugin#3]
连续点击会动画会抖动

**Comment by zhouatie** [comment]
嗯 这个是我写的一个fadeOut动画。动画没结束就频繁的显示隐藏了。本周我会想个更好的办法控制他。

**Comment by zhouatie** [comment]
@CatchaOG 你好，已经修复了，你重先下载一下或复制这个js代码。不管有无问题记得都反馈下哦

**Comment by CatchaOG** [comment]
感觉应该是点击之后显示，在点击不管多少下都要隐藏，隐藏完成之后的点击再次显示，不计算点击次数。不管怎么点都要按照显示，隐藏，显示，隐藏，这样的顺序来比较好，个人感觉而已，

**Comment by zhouatie** [comment]
嗯，现在就是现实隐藏现实隐藏的顺序来写的呀

**Comment by CatchaOG** [comment]
恩恩，辛苦了

**Comment by zhouatie** [comment]
嗯 你看下我github上的那个在线预览，觉得没问题了 反馈下 我把这个issue关了
