### ISSUE TITLE
三级联动-第三级别，可选任意地区

### ISSUE THREAD

**Issue by guilongyue** [zhouatie/plugin#5]
![image](https://user-images.githubusercontent.com/19187666/46939449-e4fa1080-d098-11e8-9e1e-3417a5b53ee3.png)

**Comment by zhouatie** [comment]
不好意思，才看到，这个周末就解决

**Comment by zhouatie** [comment]
您好！已修复您提出的bug，如果想看加了那句代码，可在commit中查看对比
